### ISSUE TITLE
Fix casing on paths in Windows

### ISSUE THREAD

**Issue by captainsafia** [nteract/jupyter-paths#14]
Follow up on some failing AppVeyor tests.

```
  1) dataDirs returns a promise that resolves to a list of directories that exist:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(3) ]
      + expected - actual

       [
         "C:\\ProgramData\\jupyter"
      -  "C:\\Python27-x64\\share\\jupyter"
         "C:\\Users\\appveyor\\AppData\\Roaming\\jupyter"
      +  "c:\\python27-x64\\share\\jupyter"
       ]

      at Assertion.assertEqual (C:\projects\jupyter-paths\node_modules\chai\lib\chai\core\assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (C:\projects\jupyter-paths\node_modules\chai\lib\chai\utils\addMethod.js:41:25)
      at C:\projects\jupyter-paths\test\jupyter_paths_spec.js:23:37
      at process._tickCallback (internal/process/next_tick.js:103:7)

  2) configDirs returns a promise that resolves to a list of directories that exist:

      AssertionError: expected [ Array(3) ] to deeply equal [ Array(3) ]
      + expected - actual

       [
         "C:\\ProgramData\\jupyter"
      -  "C:\\Python27-x64\\etc\\jupyter"
         "C:\\Users\\appveyor\\.jupyter"
      +  "c:\\python27-x64\\etc\\jupyter"
       ]
```

**Comment by lgeiger** [comment]
This was fixed in #15
